# Generated by Django 5.0.1 on 2024-04-18 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='Company',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
