# Generated by Django 5.0.1 on 2024-04-12 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_alter_customer_email'),
        ('products', '0004_alter_products_expiry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders_In',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now=True)),
                ('Customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Buyer', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
                ('Order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='which_orders', to='billing.orders_in')),
            ],
        ),
    ]
