# Generated by Django 5.0.1 on 2024-04-13 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('products', '0004_alter_products_expiry_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders_in',
            old_name='Customer_id',
            new_name='Customer',
        ),
        migrations.RemoveField(
            model_name='order_products',
            name='Order_id',
        ),
        migrations.RemoveField(
            model_name='order_products',
            name='Product_id',
        ),
        migrations.AddField(
            model_name='order_products',
            name='Order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='which_products', to='billing.orders_in'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_products',
            name='Product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='which_order', to='products.products'),
            preserve_default=False,
        ),
    ]
