# Generated by Django 5.0.1 on 2024-03-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=64)),
                ('Product_price', models.DecimalField(decimal_places=10, max_digits=19)),
                ('Quantity', models.IntegerField()),
                ('Units', models.CharField(max_length=64)),
                ('Expiry_Date', models.DateField()),
                ('Date', models.DateField(auto_now=True)),
            ],
        ),
    ]
