# Generated by Django 5.0.1 on 2024-03-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Product_price',
            field=models.DecimalField(decimal_places=5, max_digits=19),
        ),
    ]
