# Generated by Django 5.0.1 on 2024-03-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Category',
            field=models.CharField(default='Fruits and Vegetables', max_length=64),
            preserve_default=False,
        ),
    ]
